// <auto-generated />
using System;
using FAEmlak.Data.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FAEmlak.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20201224074242_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FAEmlak.Entity.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("FAEmlak.Entity.Photo", b =>
                {
                    b.Property<long>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PropertyId1")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("PropertyId1");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("FAEmlak.Entity.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<long>("CityId")
                        .HasColumnType("bigint");

                    b.Property<int?>("CityId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<long>("StateId")
                        .HasColumnType("bigint");

                    b.Property<int?>("StateId1")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PropertyId");

                    b.HasIndex("CityId1");

                    b.HasIndex("StateId1");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("FAEmlak.Entity.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.HasKey("StateId");

                    b.HasIndex("CityId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("FAEmlak.Entity.Photo", b =>
                {
                    b.HasOne("FAEmlak.Entity.Property", "Property")
                        .WithMany("Photos")
                        .HasForeignKey("PropertyId1");
                });

            modelBuilder.Entity("FAEmlak.Entity.Property", b =>
                {
                    b.HasOne("FAEmlak.Entity.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId1");

                    b.HasOne("FAEmlak.Entity.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId1");
                });

            modelBuilder.Entity("FAEmlak.Entity.State", b =>
                {
                    b.HasOne("FAEmlak.Entity.City", "City")
                        .WithMany("States")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
