// <auto-generated />
using System;
using FAEmlak.Data.Concrete.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FAEmlak.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FAEmlak.Data.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Ankara"
                        });
                });

            modelBuilder.Entity("FAEmlak.Data.FavoriteItem", b =>
                {
                    b.Property<int>("FavoriteItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavoriteItemId");

                    b.HasIndex("PropertyId");

                    b.ToTable("FavoriteItems");
                });

            modelBuilder.Entity("FAEmlak.Data.Photo", b =>
                {
                    b.Property<long>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<long>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PropertyId1")
                        .HasColumnType("int");

                    b.HasKey("PhotoId");

                    b.HasIndex("PropertyId1");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("FAEmlak.Data.Property", b =>
                {
                    b.Property<int>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area")
                        .HasColumnType("int");

                    b.Property<byte>("BathroomCount")
                        .HasColumnType("tinyint");

                    b.Property<byte>("BuildingAge")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("FloorCount")
                        .HasColumnType("tinyint");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStuff")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInSite")
                        .HasColumnType("bit");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PropertyCategory")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int>("RoomCount")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("WhichFloor")
                        .HasColumnType("tinyint");

                    b.HasKey("PropertyId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            PropertyId = 1,
                            Area = 125,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 909, DateTimeKind.Utc).AddTicks(8472),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies commodo vehicula. Vestibulum pharetra ullamcorper ante, sit amet molestie eros imperdiet consequat. Integer dapibus urna vulputate consequat posuere. Aliquam erat volutpat. Integer non malesuada lectus. Vivamus ut mattis leo. Sed ornare nunc diam, eu sollicitudin est luctus at. Integer ante mauris, imperdiet vitae leo sit amet, semper pharetra lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            FloorCount = (byte)13,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 850000,
                            PropertyCategory = 0,
                            PropertyType = 1,
                            RoomCount = 3,
                            StateId = 2,
                            Status = 0,
                            Title = "SAHRAYICEDİT İNTAŞ SİTESİNDE PARK MANZARALI 3+1 DAİRE",
                            UserId = "1",
                            WhichFloor = (byte)2
                        },
                        new
                        {
                            PropertyId = 2,
                            Area = 125,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(474),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ultricies commodo vehicula. Vestibulum pharetra ullamcorper ante, sit amet molestie eros imperdiet consequat. Integer dapibus urna vulputate consequat posuere. Aliquam erat volutpat. Integer non malesuada lectus. Vivamus ut mattis leo. Sed ornare nunc diam, eu sollicitudin est luctus at. Integer ante mauris, imperdiet vitae leo sit amet, semper pharetra lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
                            FloorCount = (byte)13,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 516152,
                            PropertyCategory = 0,
                            PropertyType = 3,
                            RoomCount = 0,
                            StateId = 2,
                            Status = 0,
                            Title = "Uğurmumcu Süper Bina Süper Fırsat",
                            UserId = "1",
                            WhichFloor = (byte)2
                        },
                        new
                        {
                            PropertyId = 3,
                            Area = 120,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(715),
                            Description = "Isı Ve Ses Yalıtımı ile Yaz Kış Ferah ve Sessiz./nLed Spot ve Dekoratif Işıklandırma ile Şık ve Kullanış﻿lı﻿.",
                            FloorCount = (byte)10,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 220000,
                            PropertyCategory = 0,
                            PropertyType = 3,
                            RoomCount = 2,
                            StateId = 2,
                            Status = 0,
                            Title = "BEYLİKDÜZÜ KALEDEN HAFTANIN EN AVANTAJLI SATILIK 2+1 DAİRESİ !!!",
                            UserId = "1",
                            WhichFloor = (byte)5
                        },
                        new
                        {
                            PropertyId = 4,
                            Area = 100,
                            BathroomCount = (byte)2,
                            BuildingAge = (byte)16,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(760),
                            Description = "Betonarme Taşıyıcı Sistemleri/nIsı Yalıtımıyla Donatılmış Dış cephe Kaplama",
                            FloorCount = (byte)13,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 419000,
                            PropertyCategory = 1,
                            PropertyType = 1,
                            RoomCount = 2,
                            StateId = 2,
                            Status = 0,
                            Title = "ROTA YAPI'DAN İSKANLI,OTOPARKLI BUTİK SİTEDE 2+1 SATILIK DAİRE",
                            UserId = "1",
                            WhichFloor = (byte)2
                        },
                        new
                        {
                            PropertyId = 5,
                            Area = 105,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(801),
                            Description = "Araçlarınız Binici Fiyatından Takas Yapılabilir",
                            FloorCount = (byte)13,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 547452,
                            PropertyCategory = 2,
                            PropertyType = 2,
                            RoomCount = 4,
                            StateId = 2,
                            Status = 0,
                            Title = "BEYLİKDÜZÜ'NDE DENİZ MANZARALI GENİŞ ULTRA LÜX DUBLEX FIRSATI",
                            UserId = "1",
                            WhichFloor = (byte)2
                        },
                        new
                        {
                            PropertyId = 6,
                            Area = 105,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(844),
                            Description = "Araçlarınız Binici Fiyatından Takas Yapılabilir",
                            FloorCount = (byte)2,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 134899,
                            PropertyCategory = 1,
                            PropertyType = 0,
                            RoomCount = 0,
                            StateId = 2,
                            Status = 0,
                            Title = "BEYLİKDÜZÜNDE 35BİN NAKİT AYLIK 1450 TL ÖDEME İLE SATILIK DAİRE",
                            UserId = "1",
                            WhichFloor = (byte)1
                        },
                        new
                        {
                            PropertyId = 7,
                            Area = 115,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(882),
                            Description = "200m2 Yaşam Alanına Sahiptir.",
                            FloorCount = (byte)1,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 220000,
                            PropertyCategory = 1,
                            PropertyType = 0,
                            RoomCount = 2,
                            StateId = 2,
                            Status = 0,
                            Title = "YILIN SON FIRSAT KELEPİR DAİRESİ 2+1 SATILIK DAİRE",
                            UserId = "1",
                            WhichFloor = (byte)1
                        },
                        new
                        {
                            PropertyId = 8,
                            Area = 105,
                            BathroomCount = (byte)1,
                            BuildingAge = (byte)26,
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 911, DateTimeKind.Utc).AddTicks(920),
                            Description = "Dairemiz Merkezi Konumda Olup Oldukça geniş Ve Kullanışlı Bir Dairedir..",
                            FloorCount = (byte)5,
                            HasBalcony = true,
                            HasStuff = false,
                            IsInSite = true,
                            Price = 315000,
                            PropertyCategory = 2,
                            PropertyType = 2,
                            RoomCount = 3,
                            StateId = 2,
                            Status = 0,
                            Title = "Emlakoffice 3+1 200m2 Merkezde Satılık Geniş Daire",
                            UserId = "1",
                            WhichFloor = (byte)2
                        });
                });

            modelBuilder.Entity("FAEmlak.Data.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Kartal"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Maltepe"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 1,
                            Name = "Pendik"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 1,
                            Name = "Ataşehir"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 2,
                            Name = "Mamak"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 2,
                            Name = "Beypazarı"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 2,
                            Name = "Keçiören"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 2,
                            Name = "Çankaya"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 2,
                            Name = "Etimesgut"
                        });
                });

            modelBuilder.Entity("FAEmlak.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a7c76394-d387-4976-be68-5decc9481b52",
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 881, DateTimeKind.Utc).AddTicks(3),
                            Email = "g181210106@sakarya.edu.tr",
                            EmailConfirmed = true,
                            FirstName = "Alperen",
                            LastName = "Derin",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEIbIf6/JKfIEiKhQl2yYE0Ji+N3anS0ZAPbccQnz3BEqV7i7azBWL/Ma7D43TYMymg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9030912f-e9d9-4af2-b29f-918481637168",
                            TwoFactorEnabled = false,
                            UserName = "g181210106@sakarya.edu.tr"
                        },
                        new
                        {
                            Id = "8e445865-a24d-4543-a8c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dacef13-c242-4005-af75-94a63539bcdd",
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 892, DateTimeKind.Utc).AddTicks(6636),
                            Email = "b181210091@sakarya.edu.tr",
                            EmailConfirmed = true,
                            FirstName = "Furkan",
                            LastName = "Ergün",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEAP7mGgL3DPxUGU5IR87LyCMCzjJpmHXxb75kmG7GQzqtzMSf4nkhgzcq1/mKNEN/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0d8034b7-7c04-4db5-9f2d-2c9467c10e36",
                            TwoFactorEnabled = false,
                            UserName = "b181210091@sakarya.edu.tr"
                        },
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba024c25-8f0e-48b5-8127-1aa91921657c",
                            Created = new DateTime(2020, 12, 30, 21, 35, 57, 900, DateTimeKind.Utc).AddTicks(5557),
                            Email = "denemeEmlak@deneme.com",
                            EmailConfirmed = true,
                            FirstName = "Deneme",
                            LastName = "Emlak",
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEM0Um23UIhvb1/UOPEJ3U/7VxAgTGJCGuDTUDr7PJ4pvUv6Kmnl3hiO+P+Z4JahS1Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "46339951-1e1d-49bd-b356-33002feca8f8",
                            TwoFactorEnabled = false,
                            UserName = "denemeEmlak@deneme.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "401a9359-6137-40c1-abec-c447523d6103",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d5efd7210",
                            ConcurrencyStamp = "ad2b88ea-1432-4898-a6f6-94a929518d74",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "8e445865-a24d-4543-a8c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "1",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d5efd7210"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FAEmlak.Data.FavoriteItem", b =>
                {
                    b.HasOne("FAEmlak.Data.Property", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FAEmlak.Data.Photo", b =>
                {
                    b.HasOne("FAEmlak.Data.Property", "Property")
                        .WithMany("Photos")
                        .HasForeignKey("PropertyId1");
                });

            modelBuilder.Entity("FAEmlak.Data.Property", b =>
                {
                    b.HasOne("FAEmlak.Data.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAEmlak.Data.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FAEmlak.Data.State", b =>
                {
                    b.HasOne("FAEmlak.Data.City", "City")
                        .WithMany("States")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FAEmlak.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FAEmlak.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FAEmlak.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FAEmlak.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
